---
baseURL: "http://qu4t3noyyzi6gqyqw7jyqwlljnfakqkmlhbvwmmisrvjuiryghs7szad.onion/"
title: "jmjordan.com"

params:
  defaultTheme: "dark"
  plausible_io: "qu4t3noyyzi6gqyqw7jyqwlljnfakqkmlhbvwmmisrvjuiryghs7szad.onion"
