---
baseURL: "https://jmjordan.com/"
languageCode: "en-us"
title: "jmjordan"
theme: "PaperMod"
paginate: 25

params:
  mainSections: ['posts']
  ShowBreadCrumbs: true
  defaultTheme: "auto"
  description: "Computer Engineer, Clemson Tiger, Swiftie"
  images: 
    - "images/banner.jpeg"
    - "images/profile.jpg"
  author: "Joanna Jordan"
  
  plausible_io: "jmjordan.com"
  updown_token: "ntzj"

  profileMode:
    enabled: false
    title: "Hi, I'm Joanna!"
    subtitle: "I 💜 technology, making things, and Taylor Swift."
    imageUrl: "images/profile.jpg"
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    
  homeInfoParams:
    title: "Hi, I'm Joanna!"
    content: > 
      - I am a Computer Engineer, proud Clemson Tiger, and loyal Swiftie.
      
      - I love technology and learning new things. 
      
      - You can find me all over the Internet if you'd like to connect.

  socialIcons: # optional
    - name: "mastodon"
      url: "https://social.lol/@jmj"
    - name: "instagram"
      url: "https://instagram.com/msjoannajordan"
    - name: "email"
      url: "mailto:hello@jmjordan.com"

menu:
  main:
    - name: "about"
      weight: 200
      url: "/about/"
    - name: "now"
      weight: 300
      url: "/now/"
    - name: "apps"
      weight: 100
      url: "/apps/"
    - name: "archive"
      weight: 400
      url: "/archive"

