baseURL = "http://example.org/"
languageCode = "en-us"
title = "jmjordan"

theme = "hugo-coder"

[params]
title = "Hi, I'm Jonathan"
author = "Jonathan Jordan"
info = "Engineer  🧡  Clemson Tiger  💜  Swiftie"
avatarurl = "images/profile.jpg"
doNotLoadAnimations = true
mainSections = []
colorscheme = "auto"

[menu]

  [[menu.main]]
  name = "About"
  weight = 200
  url = "/about/"

  [[menu.main]]
  name = "Blog"
  weight = 300
  url = "https://jmjordan.micro.blog"
  target = "_blank"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
title = "twitter"
url = "https://www.twitter.com/jmjordan"

[[params.social]]
icon = "fa fa-instagram fa-2x"
title = "instagram"
url = "https://www.instagram.com/jmjordan"