---
baseURL: "https://beta.jmjordan.com/"
languageCode: "en-us"
title: "jmjordan"
theme: "PaperMod"
paginate: 10

params:
  defaultTheme: "auto"
  
  profileMode:
    enabled: false
    
  homeInfoParams:
    title: "Hi, I'm Jonathan"
    content: > 
      I am a Computer Engineer, 
      proud [Clemson Tiger](https://clemson.edu)</a>, 
      and loyal [Swiftie](https://taylorswift.com).

  socialIcons: # optional
    - name: "twitter"
      url: "https://twitter.com/jmjordan"
    - name: "instagram"
      url: "https://instagram.com/jmjordan"
    - name: "email"
      url: "mailto:hello@jmjordan.com"

menu:
  main:
    - name: "About"
      weight: 200
      url: "/about/"

