baseURL = "http://example.org/"
languageCode = "en-us"
title = "jmjordan"

theme = "hugo-coder"

[params]
title = "Hi, I'm Jonathan"
author = "Jonathan Jordan"
info = "Engineer 🧡 Clemson Tiger 💜 Swiftie"
avatarurl = "images/profile.jpg"
doNotLoadAnimations = true
mainSections = []
colorscheme = "auto"

[params.plausibleAnalytics]
  domain = "beta.jmjordan.com"

[menu]
  [[menu.main]]
  name = "About"
  weight = 200
  url = "/about/"

  [[menu.main]]
  name = "Micro.blog"
  weight = 300
  url = "https://micro.jmjordan.com"
  target = "_blank"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
title = "twitter"
url = "https://twitter.com/jmjordan"

[[params.social]]
icon = "fa fa-instagram fa-2x"
title = "instagram"
url = "https://instagram.com/jmjordan"

[[params.social]]
icon = "fa fa-github fa-2x"
title = "github"
url = "https://github.com/jmjordan"