---
baseURL: "http://example.org/"
languageCode: "en-us"
title: "jmjordan"
theme: "hugo-coder"
enableGitInfo: true

params:
  title: "Hi, I'm Jonathan"
  author: "Jonathan Jordan"
  info: "Engineer • Swiftie • Clemson Tiger"
  avatarurl: "images/profile.jpg"
  doNotLoadAnimations: true
  mainSections: []
  colorscheme: "auto"
  commit: "https://github.com/jmjordan/jmjordan-hugo/tree"
  
  plausibleAnalytics:
    domain: "beta.jmjordan.com"
    
  social:
    - name: "Twitter"
      icon: "fa fa-twitter fa-2x"
      title: "twitter"
      url: "https://twitter.com/jmjordan"
    
    - icon: "fa fa-instagram fa-2x"
      title: "instagram"
      url: "https://instagram.com/jmjordan"
      
    - icon: "fa fa-github fa-2x"
      title: "github"
      url: "https://github.com/jmjordan"

menu:
  main:
    - name: "About"
      weight: 200
      url: "/about/"
    - name: "Micro.blog"
      weight: 300
      url: "https://micro.jmjordan.com"
      target: "_blank"

